"""Generate the README ``## Recipes`` section from per-example ``recipe.yaml``.

``recipe.yaml`` is the single source of truth for recipe metadata. This script
renders the recipe tables (grouped by category, one row per example, linking to
the runnable example directory) into the region delimited by::

    <!-- BEGIN RECIPES (generated by scripts/gen_recipe_table.py) -->
    <!-- END RECIPES -->

Usage::

    python scripts/gen_recipe_table.py            # rewrite README.md in place
    python scripts/gen_recipe_table.py --check     # exit 1 if README is stale
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tests._recipes import RECIPES, Recipe  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]
README = REPO_ROOT / "README.md"

BEGIN_MARKER = "<!-- BEGIN RECIPES (generated by scripts/gen_recipe_table.py) -->"
END_MARKER = "<!-- END RECIPES -->"

# Display order + human-readable heading for each example category.
CATEGORY_ORDER: list[tuple[str, str]] = [
    ("apis-and-ingress", "APIs and Ingress"),
    ("scheduled-and-background", "Scheduled and Background"),
    ("blob-and-file-triggers", "Blob and File Triggers"),
    ("async-apis-and-jobs", "Async APIs and Jobs"),
    ("messaging-and-pubsub", "Messaging and Pub/Sub"),
    ("streams-and-telemetry", "Streams and Telemetry"),
    ("data-and-pipelines", "Data and Pipelines"),
    ("orchestration-and-workflows", "Orchestration and Workflows"),
    ("reliability", "Reliability"),
    ("security-and-tenancy", "Security and Tenancy"),
    ("runtime-and-ops", "Runtime and Ops"),
    ("realtime", "Realtime"),
    ("ai-and-agents", "AI and Agents"),
    ("guides", "Guides"),
]


def _escape(text: str) -> str:
    return text.replace("|", "\\|")


def _row(recipe: Recipe) -> str:
    link = f"examples/{recipe.example_path}/"
    title = f"[{_escape(recipe.title)}]({link})"
    difficulty = recipe.difficulty or "—"
    return f"| {title} | {difficulty} | {_escape(recipe.description)} |"


def render(recipes: list[Recipe] = RECIPES) -> str:
    known = {slug for slug, _ in CATEGORY_ORDER}
    unknown = sorted({r.category for r in recipes} - known)
    if unknown:
        raise SystemExit(f"recipe.yaml has categories missing from CATEGORY_ORDER: {unknown}")

    lines: list[str] = [BEGIN_MARKER, ""]
    for slug, heading in CATEGORY_ORDER:
        group = sorted((r for r in recipes if r.category == slug), key=lambda r: r.title)
        if not group:
            continue
        lines.append(f"### {heading}")
        lines.append("")
        lines.append("| Recipe | Difficulty | Description |")
        lines.append("| --- | --- | --- |")
        lines.extend(_row(r) for r in group)
        lines.append("")
    lines.append(
        f"_{len(recipes)} recipes. Difficulty is carried forward from the previously "
        "hand-maintained table; unlabeled recipes show `—` pending curation ("
        "[#95](https://github.com/yeongseon/azure-functions-cookbook-python/issues/95))._"
    )
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def _splice(readme_text: str, generated: str) -> str:
    start = readme_text.find(BEGIN_MARKER)
    end = readme_text.find(END_MARKER)
    if start == -1 or end == -1:
        raise SystemExit(
            f"README markers not found; add\n{BEGIN_MARKER}\n{END_MARKER}\n"
            "around the recipe tables."
        )
    end += len(END_MARKER)
    return readme_text[:start] + generated + readme_text[end:]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate README recipe tables from recipe.yaml.")
    parser.add_argument("--check", action="store_true", help="Fail if README is out of date")
    args = parser.parse_args(argv)

    generated = render()
    current = README.read_text()
    updated = _splice(current, generated)

    if args.check:
        if current != updated:
            print(
                "README recipe tables are stale. Run: python scripts/gen_recipe_table.py",
                file=sys.stderr,
            )
            return 1
        print("README recipe tables are up to date.")
        return 0

    if current != updated:
        README.write_text(updated)
        print("Updated README recipe tables.")
    else:
        print("README recipe tables already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
